--CAU 1
CREATE DATABASE QLHANG
GO
USE QLHANG
GO
CREATE TABLE VATTU (
	MAVT CHAR(4) PRIMARY KEY NOT NULL,
	TENVT NVARCHAR(20) NOT NULL,
	DVTINH NVARCHAR(20) NOT NULL,
	SLCON INT
)
GO
CREATE TABLE HDBAN (
	MAHD VARCHAR(10) PRIMARY KEY NOT NULL,
	NGAYXUAT SMALLDATETIME NOT NULL,
	HOTENKHACH NVARCHAR(20),
)
GO
CREATE TABLE HANGXUAT(
	MAHD VARCHAR(10) NOT NULL,
	MAVT CHAR(4) NOT NULL,
	DONGIA MONEY NOT NULL,
	SLBAN INT NOT NULL,
	CONSTRAINT pk_HANGXUAT PRIMARY KEY(MAHD, MAVT)
)
GO
INSERT INTO VATTU(MAVT,TENVT,DVTINH,SLCON) VALUES(N'VT01', N'XI MANG', 'VND', 1000)
INSERT INTO VATTU(MAVT,TENVT,DVTINH,SLCON) VALUES(N'VT02', N'CAT', 'VND', 2000)
INSERT INTO VATTU(MAVT,TENVT,DVTINH,SLCON) VALUES(N'VT03', N'DA', 'VND', 4000)
INSERT INTO VATTU(MAVT,TENVT,DVTINH,SLCON) VALUES(N'VT04', N'SAT', 'VND', 3000)

INSERT INTO HDBAN(MAHD,NGAYXUAT,HOTENKHACH) VALUES(N'HD0123',CAST(N'2022-10-2'AS DATE),N'NGUYEN TI TOAN ')
INSERT INTO HDBAN(MAHD,NGAYXUAT,HOTENKHACH) VALUES(N'HD0043',CAST(N'2022-10-1'AS DATE),N'PHAN VAN DAT ')
INSERT INTO HDBAN(MAHD,NGAYXUAT,HOTENKHACH) VALUES(N'HD0001',CAST(N'2022-09-4'AS DATE),N'NGUYEN VAN ANH BA ')
INSERT INTO HDBAN(MAHD,NGAYXUAT,HOTENKHACH) VALUES(N'HD0124',CAST(N'2022-07-9'AS DATE),N'NGUYEN VAN BAO ')

INSERT INTO HANGXUAT(MAHD,MAVT,DONGIA,SLBAN) VALUES(N'HD0123',N'VT01',110000, 300)
INSERT INTO HANGXUAT(MAHD,MAVT,DONGIA,SLBAN) VALUES(N'HD0043',N'VT01',222000, 400)
INSERT INTO HANGXUAT(MAHD,MAVT,DONGIA,SLBAN) VALUES(N'HD0001',N'VT02',100000, 500)
INSERT INTO HANGXUAT(MAHD,MAVT,DONGIA,SLBAN) VALUES(N'HD0124',N'VT02',300000, 600)

--CAU 2
select top 1 MAHD, sum(DONGIA * SLBAN) as TongTien from HANGXUAT 
group by MAHD, DONGIA order by DONGIA desc

--CAU 3
CREATE FUNCTION C3 (
    @MAHD varchar(10)
)
RETURNS TABLE
AS
RETURN
    SELECT HX.MAHD, HD.NGAYXUAT, HX.MAVT, HX.DONGIA, HX.SLBAN,  
	CASE
		WHEN DATETIME(WEEKDAY,NGAYXUAT)= 1 THEN N'Thứ hai'            
		WHEN DATETIME(WEEKDAY,NGAYXUAT) = 2 THEN N'Thứ ba'
		WHEN DATETIME(WEEKDAY,NGAYXUAT) = 3 THEN N'Thứ tư'
		WHEN DATETIME(WEEKDAY,NGAYXUAT) = 4 THEN N'Thứ năm'
		WHEN DATETIME(WEEKDAY,NGAYXUAT) = 5 THEN N'Thứ sáu'
		WHEN DATETIME(WEEKDAY,NGAYXUAT) = 6 THEN N'Thứ bảy'
	ELSE N'Chủ nhật'
    END AS NGAYTHU FROM HANGXUAT HX INNER JOIN HDBAN HD ON HX.MAHD = HD.MAHD
    WHERE HX.MAHD = @MAHD;

--CAU 4
CREATE PROCEDURE C4 
@thang int, @nam int 
AS
SELECT 
SUM(SLBAN * DONGIA)
FROM HANGXUAT HX
INNER JOIN HDBAN HD ON HX.MAHD = HD.MAHD
where MONTH(HD.NGAYXUAT) = @THANG AND YEAR(HD.NGAYXUAT) = @NAM;
select top 1 MAHD, sum(DONGIA) as TongTien from HANGXUAT 
group by MAHD, DONGIA order by DONGIA desc


